import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:spendee/core/theme/theme_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:spendee/core/utils/category_utils.dart';
import 'package:spendee/services/auth_service.dart';
import 'package:spendee/Dashboard/view/premium_upgrade_screen.dart';
import '../../utils/custom_toast.dart';
import 'widget/expance_chart.dart';

class HistoricalDataScreen extends StatefulWidget {
  const HistoricalDataScreen({super.key});

  @override
  State<HistoricalDataScreen> createState() => _HistoricalDataScreenState();
}

class _HistoricalDataScreenState extends State<HistoricalDataScreen> {
  final user = FirebaseAuth.instance.currentUser;
  DateTime _selectedMonth = DateTime.now(); // Default to current month
  List<QueryDocumentSnapshot>?
  _currentMonthDocs; // To store data for PDF generation
  bool _showChart = false; // Toggle for chart visibility

  Future<void> _generatePdf(List<QueryDocumentSnapshot> docs) async {
    try {
      CustomToast.show(
        context,
        'Generating PDF Report...',
        type: ToastType.info,
      );

      final pdf = pw.Document();
      final font = await PdfGoogleFonts.interRegular();
      final fontBold = await PdfGoogleFonts.interBold();

      // Load Logo
      final logoBytes = await rootBundle.load(
        'assets/icon/Gemini_Generated_logo.png',
      );
      final logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());

      // Calculate total
      int totalAmount = 0;
      for (var doc in docs) {
        totalAmount += ((doc.data() as Map<String, dynamic>)['amount'] as num)
            .toInt();
      }

      final monthName = DateFormat('MMMM yyyy').format(_selectedMonth);

      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            pageFormat: PdfPageFormat.a4,
            buildBackground: (pw.Context context) {
              return pw.FullPage(
                ignoreMargins: true,
                child: pw.Center(
                  child: pw.Opacity(
                    opacity: 0.1,
                    child: pw.Image(logoImage, width: 300),
                  ),
                ),
              );
            },
          ),
          header: (pw.Context context) {
            return pw.Column(
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Expense Report - $monthName',
                      style: pw.TextStyle(font: fontBold, fontSize: 24),
                    ),
                    pw.Image(logoImage, width: 50, height: 50),
                  ],
                ),
                pw.SizedBox(height: 20),
              ],
            );
          },
          footer: (pw.Context context) {
            return pw.Column(
              children: [
                pw.Divider(),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Generated by Spendee',
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 10,
                        color: PdfColors.grey500,
                      ),
                    ),
                    pw.Text(
                      DateFormat('dd MMM yyyy HH:mm').format(DateTime.now()),
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 10,
                        color: PdfColors.grey500,
                      ),
                    ),
                  ],
                ),
              ],
            );
          },
          build: (pw.Context context) {
            return [
              // Summary Card
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          'Total Spent',
                          style: pw.TextStyle(
                            font: font,
                            fontSize: 12,
                            color: PdfColors.grey600,
                          ),
                        ),
                        pw.Text(
                          'INR ${NumberFormat('#,##,###').format(totalAmount)}',
                          style: pw.TextStyle(
                            font: fontBold,
                            fontSize: 20,
                            color: PdfColors.green700,
                          ),
                        ),
                      ],
                    ),
                    pw.Text(
                      '${docs.length} Transactions',
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 12,
                        color: PdfColors.grey600,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),

              // Table
              pw.TableHelper.fromTextArray(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                ),
                headerStyle: pw.TextStyle(font: fontBold),
                cellStyle: pw.TextStyle(font: font),
                headerAlignment: pw.Alignment.centerLeft,
                cellAlignment: pw.Alignment.centerLeft,
                columnWidths: {
                  0: const pw.FixedColumnWidth(100),
                  1: const pw.FlexColumnWidth(),
                  2: const pw.FixedColumnWidth(100),
                },
                headers: ['Date', 'Category', 'Amount'],
                data: List<List<dynamic>>.from(
                  docs.reversed.map((doc) {
                    final data = doc.data() as Map<String, dynamic>;
                    final date = (data['date'] as Timestamp).toDate();
                    final category = data['category'] ?? 'Other';
                    final amount = (data['amount'] as num).toInt();
                    return [
                      DateFormat('dd MMM yyyy').format(date),
                      category,
                      'INR ${NumberFormat('#,##,###').format(amount)}',
                    ];
                  }),
                ),
              ),
            ];
          },
        ),
      );

      // Share/Print the PDF
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'Spendee_Report_${monthName.replaceAll(' ', '_')}',
      );
    } catch (e) {
      debugPrint("Error generating PDF: $e");
      if (context.mounted) {
        CustomToast.show(
          context,
          'Error generating PDF: $e',
          type: ToastType.error,
        );
      }
    }
  }

  Future<void> _selectMonth(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedMonth,
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
      initialDatePickerMode:
          DatePickerMode.year, // Encourage year/month selection
      // Note: standard Flutter date picker selects a day.
      // We will just use the month/year from the selected day.
      builder: (context, child) {
        final isDark = Provider.of<ThemeProvider>(
          context,
          listen: false,
        ).isDarkMode;
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: isDark
                ? const ColorScheme.dark(
                    primary: Color(0xFF16B888), // Match app theme
                    onPrimary: Colors.white,
                    onSurface: Colors.white,
                  )
                : const ColorScheme.light(
                    primary: Color(0xFF16B888),
                    onPrimary: Colors.white,
                    onSurface: Colors.black87,
                  ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() {
        _selectedMonth = picked;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);
    final isDark = themeProvider.isDarkMode;
    final theme = Theme.of(context);

    // Calculate start and end of selected month
    final startOfMonth = DateTime(_selectedMonth.year, _selectedMonth.month, 1);
    // For end of month, go to next month day 1, then subtract 1 second (or just use < next month day 1 logic)
    final nextMonth = DateTime(
      _selectedMonth.year,
      _selectedMonth.month + 1,
      1,
    );

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        title: const Text("Historical Data"),
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.transparent,
        foregroundColor: theme.colorScheme.onSurface,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              /// Month Selector
              Container(
                width: double.infinity, // Full width for easier tapping
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 12,
                ),
                decoration: BoxDecoration(
                  color: theme.cardTheme.color,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: isDark
                        ? Colors.white.withAlpha(20)
                        : Colors.grey.shade200,
                  ),
                  boxShadow: isDark
                      ? []
                      : [
                          BoxShadow(
                            color: Colors.black.withAlpha(5),
                            blurRadius: 10,
                            offset: const Offset(0, 4),
                          ),
                        ],
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      children: [
                        Icon(
                          Icons.calendar_month_rounded,
                          color: theme.primaryColor,
                        ),
                        const SizedBox(width: 12),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "Selected Month",
                              style: TextStyle(
                                fontSize: 12,
                                color: theme.colorScheme.onSurface.withAlpha(
                                  150,
                                ),
                              ),
                            ),
                            Text(
                              DateFormat('MMMM yyyy').format(_selectedMonth),
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: theme.colorScheme.onSurface,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    TextButton(
                      onPressed: () => _selectMonth(context),
                      style: TextButton.styleFrom(
                        foregroundColor: theme.primaryColor,
                      ),
                      child: const Text("Change"),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 20),

              /// Dynamic Content
              Expanded(
                child: StreamBuilder<QuerySnapshot>(
                  stream: FirebaseFirestore.instance
                      .collection('users')
                      .doc(user!.uid)
                      .collection('expenses')
                      .where('date', isGreaterThanOrEqualTo: startOfMonth)
                      .where('date', isLessThan: nextMonth)
                      .orderBy('date', descending: true)
                      .snapshots(),
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return const Center(child: CircularProgressIndicator());
                    }

                    if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
                      return Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(
                              Icons.history,
                              size: 48,
                              color: Colors.grey[400],
                            ),
                            const SizedBox(height: 12),
                            Text(
                              "No records for this month",
                              style: TextStyle(
                                color: theme.colorScheme.onSurface.withAlpha(
                                  150,
                                ),
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      );
                    }

                    final filteredDocs = snapshot.data!.docs;
                    int totalAmount = 0;
                    for (var doc in filteredDocs) {
                      totalAmount +=
                          ((doc.data() as Map<String, dynamic>)['amount']
                                  as num)
                              .toInt();
                    }

                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        /// Summary
                        Container(
                          padding: const EdgeInsets.all(20),
                          width: double.infinity,
                          decoration: BoxDecoration(
                            gradient: LinearGradient(
                              colors: isDark
                                  ? [
                                      const Color(0xFF16B888).withOpacity(0.2),
                                      const Color(0xFF16B888).withOpacity(0.05),
                                    ]
                                  : [
                                      const Color(0xFF16B888),
                                      const Color(0xFF12A078),
                                    ],
                              begin: Alignment.topLeft,
                              end: Alignment.bottomRight,
                            ),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                "Total Spent",
                                style: TextStyle(
                                  color: isDark
                                      ? theme.colorScheme.primary
                                      : Colors.white.withAlpha(200),
                                  fontSize: 14,
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                              const SizedBox(height: 8),
                              Text(
                                "₹${NumberFormat('#,##,###').format(totalAmount)}",
                                style: TextStyle(
                                  color: isDark
                                      ? theme.colorScheme.onSurface
                                      : Colors.white,
                                  fontSize: 28,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                "${filteredDocs.length} transactions",
                                style: TextStyle(
                                  color: isDark
                                      ? theme.colorScheme.onSurface.withAlpha(
                                          150,
                                        )
                                      : Colors.white.withAlpha(200),
                                  fontSize: 13,
                                ),
                              ),
                            ],
                          ),
                        ),

                        const SizedBox(height: 20),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              _showChart ? "Analysis" : "Transactions",
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: theme.colorScheme.onSurface,
                              ),
                            ),
                            Row(
                              children: [
                                Container(
                                  height: 35,
                                  decoration: BoxDecoration(
                                    border: Border.all(
                                      color: const Color(
                                        0xFF16B888,
                                      ).withAlpha(80),
                                      width: 1,
                                    ),
                                    borderRadius: BorderRadius.circular(10),
                                    color: _showChart
                                        ? const Color(0xFF16B888).withAlpha(20)
                                        : Colors.transparent,
                                  ),
                                  child: InkWell(
                                    onTap: () {
                                      setState(() {
                                        _showChart = !_showChart;
                                      });
                                    },
                                    borderRadius: BorderRadius.circular(10),
                                    child: Padding(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 10,
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          Icon(
                                            _showChart
                                                ? Icons.bar_chart
                                                : Icons.show_chart,
                                            color: const Color(0xFF16B888),
                                            size: 18,
                                          ),
                                          const SizedBox(width: 4),
                                          const Text(
                                            "Chart",
                                            style: TextStyle(
                                              color: Color(0xFF16B888),
                                              fontWeight: FontWeight.bold,
                                              fontSize: 13,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 8),
                                SizedBox(
                                  height: 36,
                                  child: ElevatedButton.icon(
                                    onPressed: () async {
                                      final isPremium = await AuthService()
                                          .isUserPremium();
                                      if (isPremium) {
                                        _generatePdf(filteredDocs);
                                      } else {
                                        if (mounted) {
                                          showDialog(
                                            context: context,
                                            builder: (context) => AlertDialog(
                                              backgroundColor:
                                                  theme.cardTheme.color,
                                              shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(16),
                                              ),
                                              title: const Text(
                                                "Premium Feature",
                                                style: TextStyle(
                                                  fontWeight: FontWeight.bold,
                                                ),
                                              ),
                                              content: const Text(
                                                "PDF downloads are only available for Premium users. Upgrade now to unlock this and other benefits!",
                                              ),
                                              actions: [
                                                TextButton(
                                                  onPressed: () =>
                                                      Navigator.pop(context),
                                                  child: Text(
                                                    "Later",
                                                    style: TextStyle(
                                                      color: theme
                                                          .colorScheme
                                                          .onSurface
                                                          .withAlpha(150),
                                                    ),
                                                  ),
                                                ),
                                                ElevatedButton(
                                                  onPressed: () {
                                                    Navigator.pop(context);
                                                    Navigator.push(
                                                      context,
                                                      MaterialPageRoute(
                                                        builder: (context) =>
                                                            const PremiumUpgradeScreen(),
                                                      ),
                                                    );
                                                  },
                                                  style: ElevatedButton.styleFrom(
                                                    backgroundColor:
                                                        const Color(0xFF16B888),
                                                    foregroundColor:
                                                        Colors.white,
                                                    shape: RoundedRectangleBorder(
                                                      borderRadius:
                                                          BorderRadius.circular(
                                                            10,
                                                          ),
                                                    ),
                                                  ),
                                                  child: const Text("Upgrade"),
                                                ),
                                              ],
                                            ),
                                          );
                                        }
                                      }
                                    },
                                    icon: const Icon(
                                      Icons.download_rounded,
                                      size: 18,
                                    ),
                                    label: const Text("Download PDF"),
                                    style: ElevatedButton.styleFrom(
                                      backgroundColor:
                                          theme.colorScheme.primary,
                                      foregroundColor: Colors.white,
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 16,
                                      ),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                        if (_showChart) ...[
                          const SizedBox(height: 16),
                          Expanded(
                            child: SingleChildScrollView(
                              physics: const BouncingScrollPhysics(),
                              child: ExpenseChart(
                                expenses: filteredDocs,
                                selectedMonth: _selectedMonth,
                              ),
                            ),
                          ),
                        ] else ...[
                          const SizedBox(height: 12),

                          /// List
                          Expanded(
                            child: ListView.builder(
                              physics: const BouncingScrollPhysics(),
                              itemCount: filteredDocs.length,
                              itemBuilder: (context, index) {
                                final data =
                                    filteredDocs[index].data()
                                        as Map<String, dynamic>;

                                final amount = (data['amount'] as num).toInt();
                                final category =
                                    (data['category'] as String?) ?? 'Other';
                                final date = (data['date'] as Timestamp)
                                    .toDate();

                                return Container(
                                  margin: const EdgeInsets.only(bottom: 12),
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 16,
                                    vertical: 12,
                                  ),
                                  decoration: BoxDecoration(
                                    color: theme.cardTheme.color,
                                    borderRadius: BorderRadius.circular(16),
                                    border: Border.all(
                                      color: isDark
                                          ? Colors.white.withAlpha(20)
                                          : CategoryUtils.getCategoryColor(
                                              category,
                                            ).withAlpha(100),
                                      width: 1.2,
                                    ),
                                    boxShadow: isDark
                                        ? []
                                        : [
                                            BoxShadow(
                                              color: Colors.black.withAlpha(5),
                                              blurRadius: 10,
                                              offset: const Offset(0, 4),
                                            ),
                                          ],
                                  ),
                                  child: Row(
                                    children: [
                                      Container(
                                        padding: const EdgeInsets.symmetric(
                                          horizontal: 10,
                                          vertical: 6,
                                        ),
                                        decoration: BoxDecoration(
                                          color: CategoryUtils.getCategoryColor(
                                            category,
                                          ),
                                          borderRadius: BorderRadius.circular(
                                            12,
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Text(
                                              CategoryUtils.getCategoryIcon(
                                                category,
                                              ),
                                              style: const TextStyle(
                                                fontSize: 14,
                                              ),
                                            ),
                                            const SizedBox(width: 6),
                                            Text(
                                              category,
                                              style: TextStyle(
                                                color:
                                                    CategoryUtils.getCategoryTextColor(
                                                      category,
                                                      isDark,
                                                    ),
                                                fontWeight: FontWeight.w600,
                                                fontSize: 13,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      const SizedBox(width: 12),
                                      Text(
                                        DateFormat('d MMM').format(date),
                                        style: TextStyle(
                                          color: theme.colorScheme.onSurface
                                              .withAlpha(150),
                                          fontSize: 14,
                                        ),
                                      ),
                                      const Spacer(),
                                      Text(
                                        "₹${NumberFormat('#,##,###').format(amount)}",
                                        style: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: theme.colorScheme.onSurface,
                                        ),
                                      ),
                                    ],
                                  ),
                                );
                              },
                            ),
                          ),
                        ],
                      ],
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
